#!/usr/bin/env bash
# =============================================================================
# mc-bedrock-update.sh
# This script was generated by Claude AI (Anthropic) based on human instructions.
# This script is released into the public domain — no rights reserved, free to use, modify, and distribute without restriction.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
MC_USER="mc"                             # script must run as this user
MC_HOME="/home/mc"                       # all data files live here
MC_DIR="$MC_HOME"                        # server install directory (home dir IS the server dir)

BACKUP_BASE="$MC_HOME/backups"           # parent dir for nightly world backups
BACKUP_DIR=""                            # set at runtime by backup_data()
ZIPFILE="$MC_HOME/bedrock-server-latest.zip" # temp path for downloaded zip
VERSION_FILE="$MC_HOME/.installed_version" # tracks the currently installed version
LOG_DIR="$MC_HOME/logs"                  # log directory (cron redirects here too)
LOCK_FILE="$MC_HOME/.mc-update.lock"     # prevents concurrent runs

LOG_PREFIX="[mc-bedrock-update]"
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Enforce correct user
# ---------------------------------------------------------------------------
if [[ "$(id -un)" != "$MC_USER" ]]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') $LOG_PREFIX ERROR: must run as '$MC_USER', got '$(id -un)'." >&2
    exit 1
fi

log()  { echo "$(date '+%Y-%m-%d %H:%M:%S') $LOG_PREFIX $*"; }
die()  { log "ERROR: $*" >&2; exit 1; }
need() { command -v "$1" &>/dev/null || die "'$1' is required but not installed."; }

# ---------------------------------------------------------------------------
# Ensure home-dir subdirectories exist
# ---------------------------------------------------------------------------
mkdir -p "$BACKUP_BASE" "$LOG_DIR"

# ---------------------------------------------------------------------------
# Lock file — prevent concurrent runs
# ---------------------------------------------------------------------------
if ! ( set -o noclobber; echo "$$" > "$LOCK_FILE" ) 2>/dev/null; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') $LOG_PREFIX ERROR: already running (lock: $LOCK_FILE held by PID $(cat "$LOCK_FILE" 2>/dev/null))." >&2
    exit 1
fi
trap 'rm -f "$LOCK_FILE"' EXIT

# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------
need wget
need unzip

# ---------------------------------------------------------------------------
# Fetch the latest available Linux server version + download URL
# by probing Mojang's CDN directly — increments patch/minor from installed
# version until a URL returns 404, then uses the last known good one.
# ---------------------------------------------------------------------------
fetch_latest_version() {
    log "Probing Mojang CDN for latest Bedrock server version…"

    local base_url="https://www.minecraft.net/bedrockdedicatedserver/bin-linux"
    local ua="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"

    # Seed from installed version, fall back to a known baseline
    local seed
    if [[ -f "$VERSION_FILE" ]]; then
        seed=$(< "$VERSION_FILE")
    else
        seed="1.0.0.0"
    fi
    log "Seeding probe from: $seed"

    # Parse version components
    local maj min pat rev
    IFS='.' read -r maj min pat rev <<< "$seed"
    rev=${rev:-0}

    local found_url="" found_version=""
    local try_maj=$maj try_min=$min try_pat=$pat try_rev=$rev
    local attempts=0

    while [[ $attempts -lt 20 ]]; do
        local try_ver="${try_maj}.${try_min}.${try_pat}.${try_rev}"
        local try_url="${base_url}/bedrock-server-${try_ver}.zip"

        local wget_out code
        wget_out=$(wget --user-agent="$ua" --server-response --spider \
            "$try_url" 2>&1) || true
        code=$(echo "$wget_out" | awk '/^  HTTP\/[0-9]/{code=$2} END{print code}')

        if [[ "$code" == "200" ]]; then
            found_url="$try_url"
            found_version="$try_ver"
            try_rev=$(( try_rev + 1 ))
        elif [[ "$code" == "404" || -z "$code" ]]; then
            if [[ $try_rev -gt 0 ]]; then
                try_pat=$(( try_pat + 1 ))
                try_rev=0
                attempts=$(( attempts + 1 ))
            else
                break
            fi
        else
            log "WARN: Unexpected HTTP $code for $try_ver — stopping probe."
            break
        fi
    done

    if [[ -z "$found_url" ]]; then
        die "Could not find any server version at or above $seed on Mojang CDN."
    fi

    LATEST_URL="$found_url"
    LATEST_VERSION="$found_version"
    log "Available on Mojang site:  $LATEST_VERSION"
}

# ---------------------------------------------------------------------------
# Compare with installed version
# ---------------------------------------------------------------------------
get_installed_version() {
    if [[ -f "$VERSION_FILE" ]]; then
        INSTALLED_VERSION=$(< "$VERSION_FILE")
    elif [[ -f "$MC_DIR/bedrock_server" ]]; then
        # Version file missing but server binary exists — seed from the binary's
        # version string to avoid a needless reinstall on first script run
        INSTALLED_VERSION=$("$MC_DIR/bedrock_server" --version 2>/dev/null \
            | grep -oP '[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?' \
            | head -1 || true)
        if [[ -n "$INSTALLED_VERSION" ]]; then
            log "Version file absent — seeded from binary: $INSTALLED_VERSION"
            echo "$INSTALLED_VERSION" > "$VERSION_FILE"
        else
            log "WARN: Could not determine installed version from binary. Treating as uninstalled."
            INSTALLED_VERSION="none"
        fi
    else
        INSTALLED_VERSION="none"
    fi
    log "Currently installed:        $INSTALLED_VERSION"
}

# ---------------------------------------------------------------------------
# Download the new server zip
# ---------------------------------------------------------------------------
download_server() {
    # Check at least 150 MB free on the partition hosting MC_HOME
    local free_kb
    free_kb=$(df -k "$MC_HOME" | awk 'NR==2 {print $4}')
    if [[ "$free_kb" -lt 153600 ]]; then
        die "Insufficient disk space: only $((free_kb / 1024)) MB free on $MC_HOME (need 150 MB)."
    fi

    log "Downloading $LATEST_URL …"
    local rc
    wget --user-agent="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" \
        -q -O "$ZIPFILE" \
        "$LATEST_URL" 2>/tmp/mc-wget-err.txt
    rc=$?

    if [[ $rc -ne 0 ]]; then
        rm -f "$ZIPFILE"
        log "ERROR: wget failed (exit $rc): $(cat /tmp/mc-wget-err.txt)"
        die "Download failed."
    fi

    # Validate it is actually a zip file (magic bytes PK)
    if ! file "$ZIPFILE" | grep -q "Zip archive"; then
        rm -f "$ZIPFILE"
        die "Downloaded file is not a valid zip (got: $(file "$ZIPFILE" 2>/dev/null || echo unknown)). Aborting."
    fi

    log "Download complete: $ZIPFILE ($(du -h "$ZIPFILE" | cut -f1))"
}

# ---------------------------------------------------------------------------
# Backup worlds/ and server.properties
# ---------------------------------------------------------------------------
backup_data() {
    local stamp
    stamp=$(date '+%Y%m%d_%H%M%S')
    BACKUP_DIR="$BACKUP_BASE/$stamp"
    mkdir -p "$BACKUP_DIR"

    log "Backing up worlds/ and config files to $BACKUP_DIR …"
    [[ -d "$MC_DIR/worlds" ]]            && cp -a "$MC_DIR/worlds"            "$BACKUP_DIR/"
    [[ -f "$MC_DIR/server.properties" ]] && cp -a "$MC_DIR/server.properties" "$BACKUP_DIR/"
    [[ -f "$MC_DIR/permissions.json" ]]  && cp -a "$MC_DIR/permissions.json"  "$BACKUP_DIR/"
    [[ -f "$MC_DIR/allowlist.json" ]]    && cp -a "$MC_DIR/allowlist.json"     "$BACKUP_DIR/"

    # Abort if worlds/ existed in MC_DIR but didn't make it into the backup
    if [[ -d "$MC_DIR/worlds" ]] && [[ ! -d "$BACKUP_DIR/worlds" ]]; then
        die "Backup integrity check failed: worlds/ not present in $BACKUP_DIR. Aborting before install."
    fi

    log "Backup complete."
}

# ---------------------------------------------------------------------------
# Restore worlds/ and server.properties from backup
# ---------------------------------------------------------------------------
restore_data() {
    log "Restoring worlds/ and config files from $BACKUP_DIR …"
    [[ -d "$BACKUP_DIR/worlds" ]]           && cp -a "$BACKUP_DIR/worlds"            "$MC_DIR/"
    [[ -f "$BACKUP_DIR/server.properties" ]] && cp -a "$BACKUP_DIR/server.properties" "$MC_DIR/"
    [[ -f "$BACKUP_DIR/permissions.json" ]]  && cp -a "$BACKUP_DIR/permissions.json"  "$MC_DIR/"
    [[ -f "$BACKUP_DIR/allowlist.json" ]]    && cp -a "$BACKUP_DIR/allowlist.json"     "$MC_DIR/"
    log "Restore complete."
}

# ---------------------------------------------------------------------------
# Unzip the new server (preserves nothing – we restore afterwards)
# ---------------------------------------------------------------------------
install_server() {
    log "Installing new server files into $MC_DIR …"
    unzip -o "$ZIPFILE" -d "$MC_DIR" || die "unzip failed."

    # Confirm the binary is present and executable before we commit
    [[ -f "$MC_DIR/bedrock_server" ]] || die "bedrock_server binary missing after unzip — install aborted."
    chmod +x "$MC_DIR/bedrock_server"

    echo "$LATEST_VERSION" > "$VERSION_FILE"
    rm -f "$ZIPFILE"
    log "Installation complete. Zip removed."
}

# ---------------------------------------------------------------------------
# Cleanup old backups (keep last 7)
# ---------------------------------------------------------------------------
cleanup_backups() {
    log "Cleaning up old backups (keeping last 7)…"
    find "$BACKUP_BASE" -mindepth 1 -maxdepth 1 -type d \
        | sort -r \
        | tail -n +8 \
        | xargs -r rm -rf
}

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
main() {
    log "===== Bedrock update check starting ====="

    fetch_latest_version
    get_installed_version

    log "---"
    if [[ "$LATEST_VERSION" == "$INSTALLED_VERSION" ]]; then
        log "Aborted — $INSTALLED_VERSION is the latest version. No update needed."
        log "===== Done ====="
        exit 0
    fi

    log "Update available: $INSTALLED_VERSION  →  $LATEST_VERSION"

    download_server
    backup_data

    # If anything from here on fails, attempt to restore data before exiting
    trap 'log "ERROR during install — data restored from backup. Server will be started by root cron."; restore_data; exit 1' ERR

    install_server
    restore_data

    trap - ERR   # clear the error trap

    cleanup_backups

    log "Update to $LATEST_VERSION complete."
    log "===== Done ====="
}

main "$@"
